spring:
  application:
    name: todo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:app;DB_CLOSE_DELAY=-1
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: on

